Trip-Transfer-Trade/backend

module-alarm/src/main/java/com/example/module_alarm/alarm/Alarm.java
module-exchange/src/main/java/com/example/module_exchange/exchangeHistory/ExchangeHistory.java
module-exchange/src/main/java/com/example/module_exchange/exchangeRateHistory/ExchangeRateHistory.java
module-exchange/src/main/java/com/example/module_exchange/exchangeWallet/ExchangeWallet.java
module-member/src/main/java/com/example/module_member/account/Account.java
module-member/src/main/java/com/example/module_member/user/User.java
module-trip/src/main/java/com/example/module_trip/postSellProfit/PostSellProfit.java
module-trip/src/main/java/com/example/module_trip/preSellProfit/PreSellProfit.java
module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoal.java
module-trip/src/main/java/com/example/module_trip/tripOrderHistory/TripOrderHistory.java
module-trip/src/main/java/com/example/module_trip/tripStock/TripStock.java

엔티티 초기 설정
- 다른 모듈 간 참조 관계 표현 불가 : ID 값으로 저장

feat/#2-entity-set : init entity setting(#2)

---

module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmController.java
module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmHistory.java
module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmRepository.java
module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmResponseDTO.java
module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmService.java

- 유저별 알림 일괄 읽음 처리 api
- 특정 알림 읽음 처리 api

Feat/#7 : 알림 읽음 처리 api

---

module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmController.java
module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmRepository.java
module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmService.java

- user에 해당하는 전체 알림 삭제
- 특정 알림 삭제

Feat/#7 : 알림 삭제 api

---

module-exchange/src/main/java/com/example/module_exchange/clients/AccountClient.java
module-exchange/src/main/java/com/example/module_exchange/clients/TripClient.java
module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeDTO.java
module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/ExchangeCurrency.java
module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeHistory/ExchangeHistory.java
module-trip/src/main/java/com/example/module_trip/account/AccountController.java
module-trip/src/main/java/com/example/module_trip/account/AccountRepository.java
module-trip/src/main/java/com/example/module_trip/account/AccountResponseDTO.java
module-trip/src/main/java/com/example/module_trip/account/AccountService.java
module-trip/src/main/java/com/example/module_trip/account/AccountType.java
module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalController.java
module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalRequestDTO.java
module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalResponseDTO.java
module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalService.java

환전하기
- tripid X : 기본 계좌 내 환전 통화 환전 (투자를 위한 환전)
- tripid O : 목표 계좌 내 환전 통화 환전 (중간 매도매수 / 매도 후 환전)

[Fix/#8 refactor exchange] 환전하기 리팩토링

---

module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
module-exchange/src/main/java/com/example/module_exchange/exchange/transactionHistory/TransactionDTO.java

transaction request dto 수정
-> user id 에서 account id 받도록

[Fix/#31-refactor-transaction] 송금하기 리팩토링

---

module-exchange/src/main/java/com/example/module_exchange/ModuleExchangeApplication.java
module-utility/src/main/java/com/example/module_utility/response/GlobalExceptionHandler.java
module-utility/src/main/java/com/example/module_utility/response/Response.java

global exception handler 추가
필요 모듈의 application class에 스캔 코드 추가

[Feat/#41 create error]

---

module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeController.java
module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeDTO.java
module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java

[exchange dto]
기존 user id / trip id 를 통해 account id 받음
-> account id를 직접 받아올 수 있을 것 같아서 request dto에 추가

[Fix/#8-exchange-dto] 환전하기 dto 수정

---

gateway-service/src/main/resources/application-docker.yml
gateway-service/src/main/resources/application.yml
module-alarm/src/main/resources/application.yml
module-exchange/src/main/resources/application.yml
module-member/src/main/resources/application.yml
module-trip/src/main/resources/application.yml

- 로컬 개발용 yml 파일 port export 수정
- docker용 yml파일 주석 처리 후 업로드

[hotfix] local 개발을 위한 yml 임시 설정

---

build.gradle
module-exchange/src/main/java/com/example/module_exchange/clients/AccountClient.java
module-exchange/src/main/java/com/example/module_exchange/clients/MemberClient.java
module-exchange/src/main/java/com/example/module_exchange/clients/TripClient.java
module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeController.java
module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
module-exchange/src/main/java/com/example/module_exchange/exchange/transactionHistory/TransactionDTO.java
module-member/src/main/java/com/example/module_member/dto/UserResponseDto.java
module-trip/src/main/java/com/example/module_trip/ModuleTripApplication.java

- 송금 내역 조회를 위해 기본 description 추가
- 송금 보내는 입장 : 내가 누구에게 보내는지 (여행 목표 or 계좌 소유주명)를 target account number로 알아내기
- 송금 받는 입장 : 내가 누구한테 받았는지 (여행 목표 or 계좌 소유주명) 를 account id로 알아내기

[Feat/#31 description default] 송금 description default 생성 

---

module-exchange/src/main/java/com/example/module_exchange/clients/AccountClient.java
module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeController.java
module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/ExchangeCurrencyRepository.java
module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/WalletResponseDTO.java
module-exchange/src/main/java/com/example/module_exchange/redisData/stockList/StockController.java
module-member/src/main/java/com/example/module_member/dto/UserResponseDto.java
module-trip/src/main/java/com/example/module_trip/account/AccountController.java

- account client 수정
- 동일 경로에 대한 api 요청 수정
- exchange currency response dto 추가

[Feat/#63 currency list] 유저의 목표별 특정 통화 보유량 조회

---

module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmController.java
module-exchange/src/main/java/com/example/module_exchange/clients/AccountClient.java
module-exchange/src/main/java/com/example/module_exchange/clients/MemberClient.java
module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeController.java
module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
module-exchange/src/main/java/com/example/module_exchange/redisData/exchangeData/ExchangeRateController.java
module-exchange/src/main/java/com/example/module_exchange/redisData/orderBook/OrderBookController.java
module-exchange/src/main/java/com/example/module_exchange/redisData/stockList/StockController.java
module-exchange/src/main/java/com/example/module_exchange/redisData/usOrderBooK/USOrderBookController.java
module-trip/src/main/java/com/example/module_trip/account/AccountController.java

기존 api 전체 ResponseEntity<Response<T>> 으로 응답 형식 통일

[Chore/#41 set response] 응답 형식 통일

---

module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeController.java
module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/ExchangeCurrencyRepository.java
module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/WalletSummaryResponseDTO.java

[feat/#63-exchange-wallet-api]: 보유 외화 조회 api 구현

---

gateway-service/src/main/java/com/example/gateway_service/config/SecurityConfig.java
module-exchange/src/main/java/com/example/module_exchange/config/CorsMvcConfig.java

[fix/#69-cors-issue]: CORS 문제 해결

---

module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeController.java
module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java

환전, 송금하기 data access 하는 부분만 transactional로 묶여있도록 수정
total_value : exchange currency에서 조회하는 방식으로 고려

[Fix/#31-refactor] 환전/송금 transactional 수정

---

module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeBatchDTO.java
module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeController.java
module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeDTO.java
module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeHistory/ExchangeHistory.java
module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeHistory/ExchangeType.java

- 기존 exchange history entity 수정 : 중복 data 최소화, 각 통화 입장으로 수정
- 기능 구현을 위한 dto 추가
- getOrCreateExchangeCurrency : auto commit 
-> transactional로 묶어도 이미 불러올 때 commit 된 상태라 transactional 정상 작동 X
-> entity.update() 에 대한 save 처리 추가

[Feat/#80 exchange batch] 타 목표와 함께 환전하기 api

---

module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
module-exchange/src/main/java/com/example/module_exchange/exchange/transactionHistory/TransactionHistoryRepository.java

모든 transaction category 반환됨
basic만 반환하도록 수정

[Fix/#31-transaction-basic] 입출금 내역 조회 수정

---

module-exchange/src/main/java/com/example/module_exchange/exchange/transactionHistory/TransactionHistoryResponseDTO.java

[fix/#82-modify-dto] history response DTO 수정

---

module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeController.java
module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
module-exchange/src/main/java/com/example/module_exchange/exchange/transactionHistory/TransactionDTO.java

- description 입력 값 넘겨 받도록 수정
- 입력 값 없을 시 default description 생성하도록 수정

[fix/#8-modify-dto] 송금하기 dto 수정 및 description 로직 수정

---

build.gradle
module-member/src/main/java/com/example/module_member/sms/SmsController.java
module-member/src/main/java/com/example/module_member/sms/SmsService.java

[Feat/#93 send sms] sms 전송 api

---

module-member/src/main/java/com/example/module_member/user/UserController.java

feat: Implement login status API(#90)

---

build.gradle
gateway-service/src/main/java/com/example/gateway_service/filter/JwtAuthFilter.java
module-member/src/main/java/com/example/module_member/dto/CheckRequestDTO.java
module-member/src/main/java/com/example/module_member/dto/SmsSendRequestDTO.java
module-member/src/main/java/com/example/module_member/sms/RedisConfig.java
module-member/src/main/java/com/example/module_member/sms/RestTemplateConfig.java
module-member/src/main/java/com/example/module_member/sms/SmsController.java
module-member/src/main/java/com/example/module_member/sms/SmsService.java
module-member/src/main/resources/application-local.yml
module-utility/src/main/java/com/example/module_utility/response/GlobalExceptionHandler.java
module-utility/src/main/java/com/example/module_utility/response/InvalidVerificationCodeException.java

- redis 연결 setting
- 인증 코드 5분간 유효

[Feat/#93 check code] 번호 인증 api 구현

---

module-member/src/main/java/com/example/module_member/dto/SignUpRequestDto.java
module-member/src/main/java/com/example/module_member/dto/UserInfoResponseDTO.java
module-member/src/main/java/com/example/module_member/user/User.java
module-member/src/main/java/com/example/module_member/user/UserController.java
module-member/src/main/java/com/example/module_member/user/UserRepository.java
module-member/src/main/java/com/example/module_member/user/UserService.java

feat: implement userInfo API(#90)

---

build.gradle
module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmRequestDTO.java
module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmService.java
module-alarm/src/main/java/com/example/module_alarm/application/ForextAlertConsumer.java
module-alarm/src/main/java/com/example/module_alarm/application/RabbitMqConfig.java
module-alarm/src/main/java/com/example/module_alarm/fcm/FcmController.java
module-exchange/src/main/java/com/example/module_exchange/redisData/exchangeData/exchangeRateChart/ExchangeRateChartService.java
module-exchange/src/main/java/com/example/module_exchange/redisData/exchangeData/exchangeRateChart/ExchangeRateScheduler.java

- rabbitMQ 초기 설정
- redis에서 받아온 환율 데이터로 최저 환율 데이터 비교
- 최저 환율이면 알림 이벤트 생성

[Feat/#104 rate alarm] 최저 환율 알림 트리거 로직 생성

---

module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
module-exchange/src/main/java/com/example/module_exchange/exchange/transactionHistory/AccountListDTO.java

return 값에 account id 추가
-> account id로 어떤 계좌 조회할 것인지 필요

fix : add account id in return dto(#79)

---

build.gradle
module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmRequestDTO.java
module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmService.java
module-alarm/src/main/java/com/example/module_alarm/application/ForextAlertConsumer.java
module-exchange/src/main/java/com/example/module_exchange/clients/TripClient.java
module-exchange/src/main/java/com/example/module_exchange/exchange/stockTradeHistory/ProfitScheduler.java
module-exchange/src/main/java/com/example/module_exchange/exchange/stockTradeHistory/StockTradeService.java
module-exchange/src/test/java/com/example/module_exchange/learning/JsonNodeTest.java
module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoal.java
module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalAlarmDTO.java
module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalController.java
module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalProfitUpdateDTO.java
module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalService.java
module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalUpdateDTO.java

- 평가 손익 업데이트 api 작성
- 장 마감 시 (실현 손익 업데이트) + 평가 손익 업데이트
- 목표 금액 도달 체크 로직 구현
- goal rabbitmq test

[Feat/#104 goal success] 목표 도달 알림 / 평가 손익 업데이트

---

module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/AvailableDTO.java

[fix/#126-exchange-service] 환전하기 서비스 수정

---

module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmService.java
module-alarm/src/main/java/com/example/module_alarm/alarm/AlarmType.java
module-alarm/src/main/java/com/example/module_alarm/application/ForextAlertConsumer.java
module-alarm/src/main/java/com/example/module_alarm/application/RabbitMqConfig.java
module-exchange/src/main/java/com/example/module_exchange/exchange/stockTradeHistory/ProfitScheduler.java
module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalService.java

- 목표 기간 절반 지난 후에도 목표금 50%에 못미치면 알림 전송
- profit update 될 시에 함께 고려

[Feat/#104 goal half] 목표 기간 대비 목표 달성 50% 미만 알림 

---

module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/ExchangeCurrencyController.java
module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/ExchangeCurrencyService.java
module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/TripExchangeCurrencyDTO.java
module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/TripGoalDetailDTO.java
module-exchange/src/main/java/com/example/module_exchange/exchange/stockTradeHistory/StockTradeHistoryRepository.java
module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalController.java
module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalListResponseDTO.java
module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalService.java

feat: implement trip goal detail api(#135)

---

module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeController.java
module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java
module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/ExchangeGoalDTO.java
module-exchange/src/main/java/com/example/module_exchange/exchange/exchangeCurrency/ExchangeGoalListDTO.java
module-exchange/src/main/java/com/example/module_exchange/exchange/stockTradeHistory/StockTradeDTO.java

- 목표 일괄 매도
- 대금 즉시 입금
- USD/KRW -> 목표 country currency로 환전

[Feat/#132 transfer goal] 목표 즉시 매도/환전

---

module-exchange/src/main/java/com/example/module_exchange/exchange/ExchangeService.java

환율 계산 식 수정
- 외화 간 외화 계산
toAmount multiply로 통일 
: toRate : 1/toRate로 계산해야함

"fix : modify calculate rate & toAmount logic(#132)"

---

module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalController.java
module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalRepository.java
module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalService.java

유사한 목표
- 목표 기간 기준 +/- 20%
- 목표 금액 기준 +/- 20%
두 조건을 만족하는 목표 id들 return

[Feat/#144-similar-trip] 유사한 trip goal id 목록 불러오기

---

module-alarm/src/main/java/com/example/module_alarm/application/ForextAlertConsumer.java
module-alarm/src/main/java/com/example/module_alarm/application/RabbitMqConfig.java
module-exchange/src/main/java/com/example/module_exchange/clients/TripClient.java
module-exchange/src/main/java/com/example/module_exchange/exchange/stockTradeHistory/ProfitScheduler.java
module-exchange/src/main/java/com/example/module_exchange/exchange/stockTradeHistory/StockTradeService.java
module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalAlarmDTO.java
module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalController.java
module-trip/src/main/java/com/example/module_trip/tripGoal/TripGoalService.java

- 목표 기간 만료 알림 로직 구현
- exchange에서 schdeular로 테스트

[Feat/#104 goal finish] 목표 기간 만료 알림 트리거
